/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconUtils {
  IconUtils._();

  static const issIconFamily = 'ISS';
  static const launchesIconFamily = 'LAUNCHES';
  static const astronomyPostIconFamily = 'ASTRONOMY_POST';
  static const reportIconFamily = 'REPORT';
  static const String? _kFontPkg = null;

  static const IconData issIcon = IconData(0xe804, fontFamily: issIconFamily, fontPackage: _kFontPkg);
  static const IconData launchesIcon = IconData(0xe805, fontFamily: launchesIconFamily, fontPackage: _kFontPkg);
    static const IconData astronomyPostIcon = IconData(0xe806, fontFamily: astronomyPostIconFamily, fontPackage: _kFontPkg);
    static const IconData reportIcon = IconData(0xe807, fontFamily: reportIconFamily, fontPackage: _kFontPkg);
}